; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
extends = common
platform = ststm32
framework = arduino
board = genericSTM32H723VG
board_build.mcu = stm32h723vgt6
board_build.f_cpu = 480000000L
board_build.ldscript = boards/STM32H723VGTX_FLASH.ld
build_flags = 
	-DSKR_BOARD -DSKR_MINI_EZ
	-DSERIAL_UART_INSTANCE=3
	-DPIN_SERIAL_RX=PB11 -DPIN_SERIAL_TX=PB10
	-DTIMER_SERVO=TIM15
	-DSTEP_TIMER=TIM4
	-DSTEP_TIMER_CLEAR=TIM3
	-D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
	-D USE_USB_HS                
    -D USE_EMBEDDED_PHY
    -D USBCON
build_src_filter =
   +<*.h>
   +<main-${PIOENV}.cpp>
   +<test-${PIOENV}.cpp>

[env:ublox]
[env:shartlogger]
[env:sdfat]
[env:lsm6d]
[env:lis3mdl]
[env:bmp]
[env:bmi088]
[env:ms5611]

[env:lora]
platform = platformio/ststm32
framework = arduino
board = genericSTM32H723VG

[env:serialbridge]